workflows:
    android-app:
        name: loop-habits
        scripts:
            - chmod +x ./android/uhabits-android/gradlew
            - ./android/uhabits-android/gradlew assembleDebug
        artifacts:
            - app/build/outputs/**/*.apk
        publishing:
            email:
               recipients:
                   - dylansalim015@gmail.com
                   - fangwainam7@gmail.com
