name: Build, Test & Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v1
